export const diet = [
  "Balanced",
  "High-Fiber",
  "High-Protein",
  "Low-Carb",
  "Low-Fat",
  "Low-Sodium",
];

export const health = [
  "Alcohol-Cocktail",
  "Alcohol-Free",
  "Celery-Free",
  "Crustacean-Free",
  "Dairy-Free",
  "Egg-Free",
  "Fish-Free",
  "Fodmap-Free",
  "Gluten-Free",
  "Immuno-Supportive",
  "Keto-Friendly",
  "Kidney-Friendly",
  "Kosher",
  "Low-Fat-Abs",
  "Low-Potassium",
  "Low-Sugar",
  "Lupine-Free",
  "Mediterranean",
  "Mollusk-Free",
  "Mustard-Free",
  "No-Oil-Added",
  "Paleo",
  "Peanut-Free",
  "Pescatarian",
  "Pork-Free",
  "Red-Meat-Free",
  "Sesame-Free",
  "Shellfish-Free",
  "Soy-Free",
  "Sugar-Conscious",
  "Sulfite-Free",
  "Tree-Nut-Free",
  "Vegan",
  "Vegetarian",
  "Wheat-Free",
];

export const cuisineType = [
  "American",
  "Asian",
  "British",
  "Caribbean",
  "Central Europe",
  "Chinese",
  "Eastern Europe",
  "French",
  "Indian",
  "Italian",
  "Japanese",
  "Kosher",
  "Mediterranean",
  "Mexican",
  "Middle Eastern",
  "Nordic",
  "South American",
  "South East Asian",
];

export const mealType = ["Breakfast", "Dinner", "Lunch", "Snack", "Teatime"];

export const dishType = [
  "Biscuits and cookies",
  "Bread",
  "Cereals",
  "Condiments and sauces",
  "Desserts",
  "Drinks",
  "Main course",
  "Pancake",
  "Preps",
  "Preserve",
  "Salad",
  "Sandwiches",
  "Side dish",
  "Soup",
  "Starter",
  "Sweets",
];
//calories
const useQueryRecipe = () => {};

export default useQueryRecipe;
